fix(PE-6507): update wallet connectors with new sdk signing fixes
ar-io/arns-react pull request #509
Opened 2024-07-29 22:28 UTC by atticusofsparta

2024-07-29 23:20 UTC, dtfiedler requested changes

2024-07-29 23:20 UTC, dtfiedler commented on src/services/wallets/ArweaveAppWalletConnector.ts
> +    console.log(this._wallet);
```suggestion
```

2024-07-29 23:20 UTC, dtfiedler commented on src/state/actions/dispatchArIOInteraction.ts
> +} from '@ar.io/sdk';
```suggestion
} from '@ar.io/sdk/web';
```

2024-07-29 23:37 UTC, dtfiedler approved these changes

2024-07-30 18:53 UTC, kunstmusik approved these changes

2024-07-30 18:58 UTC, merged