fix(PE-6993): add ANT cu url on all ant usage
ar-io/arns-react pull request #626
Opened 2024-12-13 23:34 UTC by atticusofsparta

2024-12-16 17:35 UTC, dtfiedler approved these changes

2025-01-23 02:13 UTC, dtfiedler commented on src/utils/constants.ts
> +      GRAPHQL_URL: ARWEAVE_GRAPHQL_URL,
what's the reason we are not deferring to AO defaults for MU, SCHEDULER and GRAPHQL?

2025-01-23 02:13 UTC, dtfiedler approved these changes

2025-01-23 20:06 UTC, atticusofsparta commented on src/utils/constants.ts
> +      GRAPHQL_URL: ARWEAVE_GRAPHQL_URL,
Mostly for easy of control

2025-01-27 14:26 UTC, dtfiedler commented on src/utils/constants.ts
> +      GRAPHQL_URL: ARWEAVE_GRAPHQL_URL,
have we ever used it?

2025-01-27 14:43 UTC, dtfiedler commented on package.json
> +    "@ar.io/sdk": "^3.3.0-alpha.15",
3.3.0

2025-01-27 14:43 UTC, dtfiedler requested changes
rebase and update sdk

2025-01-27 14:48 UTC, atticusofsparta commented on src/utils/constants.ts
> +      GRAPHQL_URL: ARWEAVE_GRAPHQL_URL,
I believe its technically used whenever you spawn a process, so for example we may want to point it at goldsky instead of arweave.net. But no I don't think we use it much in normal operations, thats mainly the MU, and CU

2025-01-27 14:49 UTC, atticusofsparta commented on package.json
> +    "@ar.io/sdk": "^3.3.0-alpha.15",
https://github.com/ar-io/arns-react/pull/626/commits/139b72b87773a8d4a790dbb35ab4cfac1f9e0476

2025-01-27 17:06 UTC, dtfiedler approved these changes

2025-01-27 17:06 UTC, merged